SU-UComm/stanford-report

components/in-brief/Component.jsx
components/in-brief/manifest.json

Contains the QA fixes for the In Brief component.

Component: In Brief - QA fixes

---

components/content-carousel/Component.jsx
components/content-carousel/client.jsx
components/content-carousel/main.css
components/content-carousel/manifest.json
components/content-carousel/preview.data.json
components/content-carousel/server.jsx
global/build/global.css
global/css/_global.css
package-lock.json
package.json
packages/carousels/Carousel.jsx

Add the content carousel component.

Component: Content Carousel

---

.github/pull_request_template.md

- Add pull request template
- Whenever
- 1
1. Look at this template and the code diff

NOJIRA | Add pull request template

---

components/stories-carousel/client.jsx
components/stories-carousel/manifest.json

See subtasks under this Jira task: 
https://squizgroup.atlassian.net/browse/STANFORD-283

UAT - Stories carousel

---

components/button/Component.jsx
components/button/client.jsx
components/button/main.css
components/button/manifest.json
components/button/mocked-uris/28192.json
components/button/preview.data.json
components/button/server.jsx
packages/SVG-library/ExternalArrowUnstyled.jsx
packages/SVG-library/SVG.js
packages/links/ExternalLink.jsx
packages/links/LinkButton.jsx
packages/links/Links.jsx

- Add reusable package LinkedButton
- Add Button component (component service)
- Soon
- 7
1. Look at code
2. Go to https://sug-web.matrix.squiz.cloud/report/development/yvonnes-test-page to see the 4 examples, or try adding the Button component into your own test page
- JIRA ticket(s) - STANFORD-560

STANFORD-560 | Button component

---

components/image-gallery-modal/manifest.json

First test of the global components redeploy is the image gallery modal component.

updating the image gallery modal component as the first test

---

components/cta-cards-block/Component.jsx
components/cta-cards-block/client.jsx
components/cta-cards-block/main.css
components/cta-cards-block/manifest.json
components/cta-cards-block/mocked-uris/28192.json
components/cta-cards-block/preview.data.json
components/cta-cards-block/server.jsx
global/build/global.css
packages/SVG-library/ChevronRight.jsx
packages/card/CtaCard.jsx
packages/links/LinkButton.jsx

- CTA Cards Block component
- Whenever you need it
- 5
1. See my test page
https://sug-web.matrix.squiz.cloud/report/development/yvonnes-test-page
2. Test different responsive breakpoints
3. Test both light and dark mode
4. Change background to #f4f4f4 (fog light) in the inspector and see that the card still look good - this is simulating the future Campaign page. Below is my test:
5. Add the component on your own test page and see the user experience
6. Look at code
- JIRA ticket(s) - STANFORD-419

STANFORD-419 | CTA cards block

---

global/build/global.css
global/css/_global.css

- Add the charset for UTF-8 to force nice quotes. These are used in In the News and Image quotes.
JIRA ticket(s) - [STANFORD-1048](https://squizgroup.atlassian.net/browse/STANFORD-1048)

Add charset to global CSS

---

packages/metadata-fields/BasicMetadata.jsx
packages/metadata-fields/FeaturedMetadata.jsx

- Fix for the Metadata fields component >> Copy link button. As per STANFORD-1008
- asap
- 5
1. Please see STANFORD-1008 for test instructions.
- JIRA ticket(s) - https://squizgroup.atlassian.net/browse/STANFORD-1008

Fixes to STANFORD-1008 Copy Link

---

packages/grids/MultiColumnGrid.test.jsx

- This pull request fixes a failing test, which causes the CI/CD process to error.
- ASAP
- 3 - not blocking deployments, but does cause errors in the Github Actions tab
1. Check out this branch
2. Run `npm run test` locally 
3. All tests should pass. Please note that some take a while to run, this sometimes shows as red in the console, but is not an error, it's just an indication the tests took some time to complete.
- JIRA ticket(s) - STANFORD-1069
- This also needs to be merged into `develop` to fix that pipeline, however this should be merged into `master` first. Develop has a conflict in the global files with this branch, so once this branch is merged into master, it would be best to merge master back into develop.
- @broleomo @iamrentman

STANFORD-1069 - Fix failing CI/CD tests

---

components/leadership-hero/Component.jsx
components/leadership-hero/frontend.html
components/leadership-hero/manifest.json

- Addition of Topic linking to the leadership hero component.
As per steps detailed on ticket https://squizgroup.atlassian.net/browse/STANFORD-1108?focusedCommentId=4997879
- JIRA ticket(s) - [STANFORD-1108](https://squizgroup.atlassian.net/browse/STANFORD-1108)
- Replicated from basic-story-hero
- @broleomo @iamrentman this will go to Deb first for QA.

Leadership topic linking

---

components/sidebar-navigation/Component.jsx
components/sidebar-navigation/client.jsx
components/sidebar-navigation/manifest.json
global/build/global.css

- Make button text black in dark mode
- Adjust spacing below button
- Increment for dxp deploy

Quick fix adjustments for sidebar-navigation

---

components/sidebar-navigation/client.jsx
components/sidebar-navigation/manifest.json

- Use prod endpoint URL
- Increment for re-deploy

Change sidebar-navigation endpoint URL

---

components/combined-content-grid/manifest.json
components/events-section/manifest.json
components/featured-content/manifest.json
components/horizontal-video-testimonials/manifest.json
components/single-featured-content/manifest.json
global/build/global.css
packages/card/HorizontalCard.jsx
packages/card/HorizontalVideoCard/HorizontalVideoCard.jsx
packages/media/MediaRatio.jsx

Changes the aspect ratio of the large, feature-size card to 3/2 from 16/9.
ASAP
3
Julia & Megan have reviewed and approved the display on [this page](https://news.stanford.edu/developreport/homepage/_nocache) 
- [UCP-3653](https://stanfordits.atlassian.net/browse/UCP-3653)
[UCP-3653]: https://stanfordits.atlassian.net/browse/UCP-3653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature card image aspect ration 16/9 to 3:2

---

components/image-gallery-modal/manifest.json
global/build/global.css
global/css/_global.css

- Remove blue focus ring around image and control `<div>`s within modal on mobile
- ASAP
- 3
- [UCP-3621](https://stanfordits.atlassian.net/browse/UCP-3621)
[UCP-3621]: https://stanfordits.atlassian.net/browse/UCP-3621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Image gallery modal focus styles

---

components/media-carousel/Component.jsx
components/media-carousel/manifest.json
components/media-carousel/preview.data.json
global/build/global.css
global/css/_global.css
packages/card/MediaCard.jsx
packages/utils/formatMediaCardDataMatrix.js

Adds a "Magazine" option to the Type field and adjusts the code accordingly for appropriate display. I've also adjusted the component so the shadow on the book images doesn't get cut off by the container.
- ASAP
3
1. Go here: https://news.stanford.edu/developreport/university-news/_nocache
2. The Media Carousel is the first component on the page and the first item is selected as "Magazine" type.
3. Go to the back end of this page and confirm that "Magazine" is an option in the Type field and it appropriately displays "Featured Reading" and Magazine. https://news.stanford.edu/developreport/university-news/_admin
4. Review code.
[UCP-3558](https://stanfordits.atlassian.net/browse/UCP-3558)
[UCP-3558]: https://stanfordits.atlassian.net/browse/UCP-3558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …

Media Carousel magazine option

---

global/build/global.css
global/css/_global.css

- Removes overflow visible on swiper causing horizontal scroll issue on mobile

Hotfix: Media Carousel overflow

---

components/image-gallery-modal/Component.jsx
components/image-gallery-modal/manifest.json
components/image-gallery-modal/preview.data.json
packages/card/MediaCard.jsx

- Adds summaryAlign field to component with left and center values
- Add style handling for summaryAlign field to component markup
- Adjusts preview data for testing
- ASAP
3
1. This dev page uses the updated version of the component: https://news.stanford.edu/developreport/test-page/
2. add _admin to the page URL above, change the "Summary alignment" field, Save, preview the page...did it work?
3. Review the code in this PR.
[UCP-3802](https://stanfordits.atlassian.net/browse/UCP-3802)
[UCP-3802]: https://stanfordits.atlassian.net/browse/UCP-3802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add summary text alignment to Image Gallery with Modal

---

components/link-list/Component.jsx
components/link-list/manifest.json
components/popular-stories-cf/Component.jsx
components/popular-stories-cf/manifest.json
global/build/global.css

- Add id to `link-list` and `popular-stories`
ASAP
5
1. See [UCP-3385](https://stanfordits.atlassian.net/browse/UCP-3385) for details
2. Review code changes
[UCP-3385](https://stanfordits.atlassian.net/browse/UCP-3385)
[UCP-3385]: https://stanfordits.atlassian.net/browse/UCP-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add IDs for GTM tracking

---

components/media-carousel/manifest.json
components/media-carousel/preview.data.json
components/media-feature/Component.jsx
components/media-feature/manifest.json
components/media-feature/preview.data.json
global/build/global.css
packages/card/MediaCard.jsx

- Add "Magazine" option and appropriate logic to component
- - Add "Magazine" option to manifest
- Adjustments to preview data for testing
ASAP
5
1. [UCP-3857](https://stanfordits.atlassian.net/browse/UCP-3857)
2. Review code changes here or pull down locally
[UCP-3857](https://stanfordits.atlassian.net/browse/UCP-3857)
[UCP-3857]: https://stanfordits.atlassian.net/browse/UCP-3857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UCP-3857]: https://stanfordits.atlassian.net/browse/UCP-3857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add “Magazine” media type to Single Feature Media component 

---

components/leadership-hero/Component.jsx
components/leadership-hero/frontend.html
components/leadership-hero/manifest.json

Update heading styles to match basic story

HOTFIX: Leadership Hero heading size adjustment

---

global/build/global.css
global/css/_global.css

- Add `[data-component="featured-content-vv"]` to contextual styles in _global.css

HOTFIX: featured content with vertical video missing contextual styles

---

components/campaign-hero/Component.jsx
components/campaign-hero/manifest.json
components/campaign-hero/styles.js
components/horizontal-video-testimonials/Component.jsx
components/horizontal-video-testimonials/alwaysDark.data.json
components/horizontal-video-testimonials/manifest.json
components/horizontal-video-testimonials/styles.js
components/interactive-photo-card/Component.jsx
components/interactive-photo-card/alwaysDark.data.json
components/interactive-photo-card/manifest.json
components/multicolumn-fact-panel/Component.jsx
components/multicolumn-fact-panel/manifest.json
components/multicolumn-fact-panel/preview.data.json
components/vertical-videos-panel/Component.jsx
components/vertical-videos-panel/alwaysDark.data.json
components/vertical-videos-panel/manifest.json
components/vertical-videos-panel/styles.js
global/build/global.css
global/css/_global.css
packages/__globalPreview/campaign-always-dark.html
packages/card/CardThumbnail.jsx
packages/card/HorizontalVideoCard/HorizontalVideoCard.jsx
packages/card/HorizontalVideoCard/HorizontalVideoCard.styles.js
packages/card/VerticalVideoCard/VerticalVideoCard.jsx
packages/card/VerticalVideoCard/VerticalVideoCard.styles.js

This PR adds adjustments for campaign pages to present in dark mode only. A page-level class was added to make the background black and the following components were updated with an `alwaysDark` field/prop:
- Horizontal Video Testimonials
- Interactive Photo Card
- Multicolumn Fact Panel
- Vertical Videos Panel
Yesterday
11
1. Review code here
2. [Demo/test page](https://news.stanford.edu/developreport/campaigns/copy-campaign-page-example-two/_nocache) – add /_admin to review the editorial  
[UCP-4145](https://stanfordits.atlassian.net/browse/UCP-4145)
[UCP-4145]: https://stanfordits.atlassian.net/browse/UCP-4145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Research matters dark components

---

global/build/global.css
global/css/_global.css

- Add styles for .center class on campaign pages

HOTFIX Center campaign text

---

global/build/global.css
global/css/_global.css

- Adjust selector for centering .center class on campaign pages.

Campaign center text adjust

---

components/interactive-photo-card/Component.jsx
components/interactive-photo-card/manifest.json
global/build/global.css

- Adds max and min widths to Interactive Video Card content card container 
ASAP
11
1. Code here.
2. Test pages – [here](https://news.stanford.edu/developreport/campaigns/research-at-stanford/_nocache) and [here](https://news.stanford.edu/developreport/campaigns/horizontal-scroll-testing/_nocache)
[UCP-4147](https://stanfordits.atlassian.net/browse/UCP-4171)
[UCP-4147]: https://stanfordits.atlassian.net/browse/UCP-4147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Bug/ucp 4147  mobile h scroll

---

global/build/global.css
global/css/_global.css

- Add text color style override for Multicolumn Image on alwaysDark pages

BUG: Multicolumn Image caption fix for alwaysDark

---

global/build/global.css
global/css/_global.css

- Update selector for Multicolumn Image captions, edge changes wrapper from div to section

Update mci caption selector
